# Travis CI Java documentation can be found in:
# https://docs.travis-ci.com/user/languages/java/

# This enables the 'defaults' to test java applications:
language: java

script: "mvn cobertura:cobertura"

# We can specify a list of JDKs to be used for testing
# A list of available JDKs in Trusty can be seed in:
# https://docs.travis-ci.com/user/reference/trusty/#jvm-clojure-groovy-java-scala-images
jdk:
 - oraclejdk8
 - oraclejdk9

after_success:
 - bash <(curl -s https://codecov.io/bash)
